require:
  - standard
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

inherit_gem:
  standard: config/base.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**/*
    - public/**/*
    - vendor/**/*

Performance:
  Enabled: true
Rails:
  Enabled: true
RSpec:
  Enabled: true
